/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package juego_ui;

import javax.swing.DefaultListModel;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import jugador_dato.Jugador;
import pokemon_dato.Agua;
import pokemon_dato.Fuego;
import pokemon_dato.Normal;
import pokemon_dato.Pokemon;
import pokemon_pokedex.ListaCircularPokemon;
import pokemon_pokedex.ListaDCPokedex;

/**
 *
 * @author Ignac
 */
public class VentanaElegirPokedex extends JFrame {

    /**
     * Creates new form VentanaElegirPokedex
     */
    Jugador jugador;
    ListaCircularPokemon lstCircularPokemon = new ListaCircularPokemon();

    DefaultListModel<String> modeloPokedex = new DefaultListModel<>();

    public VentanaElegirPokedex(Jugador jugador) {
        initComponents();

        lstCircularPokemon.inserta(new Normal("Pikachu", 1));
        lstCircularPokemon.inserta(new Normal("Jigglypuff", 2));
        lstCircularPokemon.inserta(new Normal("Snorlax", 3));
        lstCircularPokemon.inserta(new Fuego("Charmander", 4));
        lstCircularPokemon.inserta(new Fuego("Vulpix", 5));
        lstCircularPokemon.inserta(new Fuego("Growlithe", 6));
        lstCircularPokemon.inserta(new Agua("Squirtle", 7));
        lstCircularPokemon.inserta(new Agua("Psyduck", 8));
        lstCircularPokemon.inserta(new Agua("Lapras", 9));

        this.setLocationRelativeTo(null);
        this.setVisible(true);

        this.jugador = jugador;

        jLabelNombreEntrenador.setText(jugador.getNombreJugador());

        jLabelImagenPokemon.setText(lstCircularPokemon.pokemonActual().getNombre());

        jLabelNombrePokemon.setText("Nombre: " + lstCircularPokemon.pokemonActual().getNombre());
        jLabelTipo.setText("Tipo: " + lstCircularPokemon.pokemonActual().getTipo());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabelImagenPokemon = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabelNombrePokemon = new javax.swing.JLabel();
        jLabelTipo = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabelPokemon = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabelNombreEntrenador = new javax.swing.JLabel();
        btnAgregarPokemon = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        btnSiguiente = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jListaPokemon = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(834, 600));

        jPanel1.setBackground(new java.awt.Color(27, 110, 188));
        jPanel1.setPreferredSize(new java.awt.Dimension(850, 632));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jLabelImagenPokemon.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 12)); // NOI18N
        jLabelImagenPokemon.setForeground(new java.awt.Color(0, 0, 0));
        jLabelImagenPokemon.setText("IMAGEN POKEMON");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(98, 98, 98)
                .addComponent(jLabelImagenPokemon)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(139, 139, 139)
                .addComponent(jLabelImagenPokemon)
                .addContainerGap(138, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(238, 130, 304, -1));

        jPanel4.setBackground(new java.awt.Color(3, 64, 113));

        jLabelNombrePokemon.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        jLabelNombrePokemon.setForeground(new java.awt.Color(255, 255, 255));
        jLabelNombrePokemon.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabelNombrePokemon.setText("Nombre: ");
        jLabelNombrePokemon.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabelNombrePokemon.setName("prueba"); // NOI18N

        jLabelTipo.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        jLabelTipo.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTipo.setText("Tipo:");

        jLabel4.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Vida:");

        jLabel5.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Ataque:");

        jLabel6.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Defensa:");

        jLabel7.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Ataque Especial: ");

        jLabel8.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Defensa Especia:l");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jLabel7)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addComponent(jLabelNombrePokemon)
                    .addComponent(jLabelTipo))
                .addContainerGap(92, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabelNombrePokemon)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelTipo)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addComponent(jLabel8)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        jLabelNombrePokemon.getAccessibleContext().setAccessibleName("Nombre: ");

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(578, 130, -1, -1));

        jLabel1.setFont(new java.awt.Font("Yu Gothic UI", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("POKEDEX");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 80, 178, 40));

        jLabelPokemon.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 24)); // NOI18N
        jLabelPokemon.setForeground(new java.awt.Color(255, 255, 51));
        jLabelPokemon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelPokemon.setText("POKEMON");
        jLabelPokemon.setPreferredSize(new java.awt.Dimension(113, 32));
        jPanel1.add(jLabelPokemon, new org.netbeans.lib.awtextra.AbsoluteConstraints(303, 92, 181, -1));

        jLabel3.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("DETALLES");
        jLabel3.setPreferredSize(new java.awt.Dimension(104, 32));
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(578, 92, 218, -1));

        jLabelNombreEntrenador.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 24)); // NOI18N
        jLabelNombreEntrenador.setForeground(new java.awt.Color(255, 255, 255));
        jLabelNombreEntrenador.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelNombreEntrenador.setLabelFor(this);
        jLabelNombreEntrenador.setText("ENTRENADOR");
        jLabelNombreEntrenador.setPreferredSize(new java.awt.Dimension(149, 32));
        jPanel1.add(jLabelNombreEntrenador, new org.netbeans.lib.awtextra.AbsoluteConstraints(222, 36, 345, -1));

        btnAgregarPokemon.setBackground(new java.awt.Color(240, 85, 75));
        btnAgregarPokemon.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 16)); // NOI18N
        btnAgregarPokemon.setForeground(new java.awt.Color(255, 255, 255));
        btnAgregarPokemon.setText("AGREGAR");
        btnAgregarPokemon.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnAgregarPokemon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarPokemonActionPerformed(evt);
            }
        });
        jPanel1.add(btnAgregarPokemon, new org.netbeans.lib.awtextra.AbsoluteConstraints(238, 462, 304, 43));

        jButton2.setBackground(new java.awt.Color(40, 40, 40));
        jButton2.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 16)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("SALIR");
        jButton2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton2.setPreferredSize(new java.awt.Dimension(48, 28));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 462, 170, 43));

        btnSiguiente.setBackground(new java.awt.Color(255, 255, 255));
        btnSiguiente.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 16)); // NOI18N
        btnSiguiente.setForeground(new java.awt.Color(0, 0, 0));
        btnSiguiente.setText("SIGUIENTE");
        btnSiguiente.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnSiguiente.setPreferredSize(new java.awt.Dimension(83, 28));
        btnSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSiguienteActionPerformed(evt);
            }
        });
        jPanel1.add(btnSiguiente, new org.netbeans.lib.awtextra.AbsoluteConstraints(578, 462, 218, 43));

        jScrollPane2.setBackground(new java.awt.Color(3, 64, 113));
        jScrollPane2.setPreferredSize(new java.awt.Dimension(85, 306));

        jListaPokemon.setBackground(new java.awt.Color(3, 64, 113));
        jListaPokemon.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 26)); // NOI18N
        jListaPokemon.setForeground(new java.awt.Color(255, 255, 255));
        jListaPokemon.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "1 - ...", "2 - ...", "3 - ...", "4 - ..." };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(jListaPokemon);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 132, 170, 291));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 856, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 573, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarPokemonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarPokemonActionPerformed

        if (jugador.getPokedex().getSize() < 4) {
            Pokemon pokemonActual = lstCircularPokemon.pokemonActual();
            jugador.getPokedex().inserta(pokemonActual);
            JOptionPane.showMessageDialog(this, pokemonActual.getNombre() + " agregado a tu pokedex.");

            // Actualiza la lista de Pokémon en la interfaz
            cargarListaPokemon();
        } else {
            JOptionPane.showMessageDialog(null, "Pokedex Lleno");
        }

    }//GEN-LAST:event_btnAgregarPokemonActionPerformed

    private void btnSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSiguienteActionPerformed
        // Mover al siguiente Pokémon en la lista
        lstCircularPokemon.siguientePokemon();

        // Depuración: Imprimir información del Pokémon actual
        System.out.println(lstCircularPokemon.pokemonActual());

        // Actualiza los labels con la información del Pokémon actual
        jLabelImagenPokemon.setText(lstCircularPokemon.pokemonActual().getNombre());
        jLabelNombrePokemon.setText("Nombre: " + lstCircularPokemon.pokemonActual().getNombre());
        jLabelTipo.setText("Tipo: " + lstCircularPokemon.pokemonActual().getTipo());

    }//GEN-LAST:event_btnSiguienteActionPerformed

    private void cargarListaPokemon() {
        DefaultListModel<String> model = new DefaultListModel<>();

        model.addElement(lstCircularPokemon.pokemonActual().getNombre());
        lstCircularPokemon.siguientePokemon();
        jListaPokemon.setModel(model);
    }


    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    //Metodo para cargar los pokemones de la lista

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarPokemon;
    private javax.swing.JButton btnSiguiente;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabelImagenPokemon;
    private javax.swing.JLabel jLabelNombreEntrenador;
    private javax.swing.JLabel jLabelNombrePokemon;
    private javax.swing.JLabel jLabelPokemon;
    private javax.swing.JLabel jLabelTipo;
    private javax.swing.JList<String> jListaPokemon;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables

}
